name: demo-graphql
services:
  products:
    container_name: products
    build: ./services/products
    ports:
      - "4001:4000"
      
  users:
    container_name: users
    build: ./services/users
    ports:
      - "4002:4000"

  # router:
  #   platform: linux/amd64
  #   environment:
  #     - ENABLE_EXPOSE_QUERY_PLAN_ENV=true
  #     - APOLLO_KEY=${APOLLO_KEY}
  #     - APOLLO_GRAPH_REF=${APOLLO_GRAPH_REF}
  #   build: 
  #     context: ./router
  #     args:
  #       - SUBS_EXAMPLE=${SUBS_EXAMPLE}
  #       - FRAMEWORK=${FRAMEWORK}
  #   security_opt:
  #     - seccomp:unconfined
  #   ports:
  #     - "4040:4040"
  #   volumes:
  #     - ./router:/volume
